const expectedColumnInFile: string[] = [
    "PATNR",
    "Leuko",
    "Hb",
    "MCV",
    "Trom",
    "BSE",
    "Age",
    "RF",
    "aCCP",
    "Sex",
    "Pijn_acromioclaviaculair R",
    "Pijn_acromioclaviaculair L",
    "Zwelling_acromioclaviaculair R",
    "Zwelling_acromioclaviaculair L",
    "Pijn_bovenste spronggewricht rechts",
    "Pijn_bovenste spronggewicht links",
    "Zwelling_bovenste spronggewricht rechts",
    "Zwelling_bovenste spronggewicht links",
    "Pijn_onderste spronggewricht rechts",
    "Pijn_onderste spronggewricht links",
    "Zwelling_onderste spronggewricht rechts",
    "Zwelling_onderste spronggewricht links",
    "Pijn_elleboog R",
    "Pijn_Elleboog L",
    "Zwelling_elleboog R",
    "Zwelling_Elleboog L",
    "Pijn_IP rechts",
    "Pijn_IP links",
    "Pijn_pip 2 rechts hand",
    "Pijn_pip 2 links hand",
    "Pijn_pip 3 rechts hand",
    "Pijn_pip 3 links hand",
    "Pijn_pip 4 links hand",
    "Pijn_pip 4 rechts hand",
    "Pijn_pip 5 rechts hand",
    "Pijn_pip 5 links hand",
    "Pijn_dip 2 rechts",
    "Pijn_dip 2 links",
    "Pijn_dip 3 rechts",
    "Pijn_dip 3 links",
    "Pijn_dip 4 rechts",
    "Pijn_dip 4 links",
    "Pijn_dip 5 rechts",
    "Pijn_dip 5 links",
    "Zwelling_IP rechts",
    "Zwelling_IP links",
    "Zwelling_pip 2 rechts hand",
    "Zwelling_pip 2 links hand",
    "Zwelling_pip 3 rechts hand",
    "Zwelling_pip 3 links hand",
    "Zwelling_pip 4 rechts hand",
    "Zwelling_pip 4 links hand",
    "Zwelling_pip 5 rechts hand",
    "Zwelling_pip 5 links hand",
    "Zwelling_dip 2 rechts",
    "Zwelling_dip 2 links",
    "Zwelling_dip 3 rechts",
    "Zwelling_dip 3 links",
    "Zwelling_dip 4 rechts",
    "Zwelling_dip 4 links",
    "Zwelling_dip 5 rechts",
    "Zwelling_dip 5 links",
    "Pijn_knie rechts",
    "Pijn_knie links",
    "Zwelling_knie rechts",
    "Zwelling_knie links",
    "Pijn_mcp 1 rechts",
    "Pijn_mcp 1 links",
    "Pijn_mcp 2 rechts",
    "Pijn_mcp 2 links",
    "Pijn_mcp 3 rechts",
    "Pijn_mcp 3 links",
    "Pijn_mcp 4 rechts",
    "Pijn_mcp 4 links",
    "Pijn_mcp 5 links",
    "Pijn_mcp 5 rechts",
    "Zwelling_mcp 1 rechts",
    "Zwelling_mcp 1 links",
    "Zwelling_mcp 2 rechts",
    "Zwelling_mcp 2 links",
    "Zwelling_mcp 3 rechts",
    "Zwelling_mcp 3 links",
    "Zwelling_mcp 4 rechts",
    "Zwelling_mcp 4 links",
    "Zwelling_mcp 5 rechts",
    "Zwelling_mcp 5 links",
    "Pijn_tarsometatarsaal R",
    "Pijn_tarsometatarsaal L",
    "Zwelling_tarsometatarsaal R",
    "Zwelling_tarsometatarsaal L",
    "Pijn_mtp 1 rechts",
    "Pijn_mtp 1 links",
    "Pijn_mtp 2 rechts",
    "Pijn_mtp 2 links",
    "Pijn_mtp 3 rechts",
    "Pijn_mtp 3 links",
    "Pijn_mtp 4 rechts",
    "Pijn_mtp 4 links",
    "Pijn_mtp 5 rechts",
    "Pijn_mtp 5 links",
    "Zwelling_mtp 1 rechts",
    "Zwelling_mtp 1 links",
    "Zwelling_mtp 2 rechts",
    "Zwelling_mtp 2 links",
    "Zwelling_mtp 3 rechts",
    "Zwelling_mtp 3 links",
    "Zwelling_mtp 4 rechts",
    "Zwelling_mtp 4 links",
    "Zwelling_mtp 5 rechts",
    "Zwelling_mtp 5 links",
    "Pijn_sternoclaviculair R",
    "Pijn_sternoclaviculair L",
    "Zwelling_sternoclaviculair R",
    "Zwelling_sternoclaviculair L",
    "Pijn_schouder R",
    "Pijn_schouder L",
    "Zwelling_schouder R",
    "Zwelling_schouder L",
    "Pijn_temporomandibulair R",
    "Pijn_temporomandibulair L",
    "Zwelling_temporomandibulair R",
    "Zwelling_temporomandibulair L",
    "Pijn_pols R",
    "Pijn_pols L",
    "Zwelling_pols R",
    "Zwelling_pols L",
    "Pijn_heup rechts",
    "Pijn_heup links",
] as const;

const lcat = [
    "Zwelling_Elleboog L_negative",
    "Zwelling_Elleboog L_positive",
    "Zwelling_IP links_negative",
    "Zwelling_IP links_positive",
    "Zwelling_IP rechts_negative",
    "Zwelling_IP rechts_positive",
    "Zwelling_acromioclaviaculair L_negative",
    "Zwelling_acromioclaviaculair L_positive",
    "Zwelling_acromioclaviaculair R_negative",
    "Zwelling_acromioclaviaculair R_positive",
    "Zwelling_bovenste spronggewicht links_negative",
    "Zwelling_bovenste spronggewicht links_positive",
    "Zwelling_bovenste spronggewricht rechts_negative",
    "Zwelling_bovenste spronggewricht rechts_positive",
    "Zwelling_dip 2 links_negative",
    "Zwelling_dip 2 links_positive",
    "Zwelling_dip 2 rechts_negative",
    "Zwelling_dip 2 rechts_positive",
    "Zwelling_dip 3 links_negative",
    "Zwelling_dip 3 links_positive",
    "Zwelling_dip 3 rechts_negative",
    "Zwelling_dip 3 rechts_positive",
    "Zwelling_dip 4 links_negative",
    "Zwelling_dip 4 links_positive",
    "Zwelling_dip 4 rechts_negative",
    "Zwelling_dip 4 rechts_positive",
    "Zwelling_dip 5 links_negative",
    "Zwelling_dip 5 links_positive",
    "Zwelling_dip 5 rechts_negative",
    "Zwelling_dip 5 rechts_positive",
    "Zwelling_elleboog R_negative",
    "Zwelling_elleboog R_positive",
    "Zwelling_knie links_negative",
    "Zwelling_knie links_positive",
    "Zwelling_knie rechts_negative",
    "Zwelling_knie rechts_positive",
    "Zwelling_mcp 1 links_negative",
    "Zwelling_mcp 1 links_positive",
    "Zwelling_mcp 1 rechts_negative",
    "Zwelling_mcp 1 rechts_positive",
    "Zwelling_mcp 2 links_negative",
    "Zwelling_mcp 2 links_positive",
    "Zwelling_mcp 2 rechts_negative",
    "Zwelling_mcp 2 rechts_positive",
    "Zwelling_mcp 3 links_negative",
    "Zwelling_mcp 3 links_positive",
    "Zwelling_mcp 3 rechts_negative",
    "Zwelling_mcp 3 rechts_positive",
    "Zwelling_mcp 4 links_negative",
    "Zwelling_mcp 4 links_positive",
    "Zwelling_mcp 4 rechts_negative",
    "Zwelling_mcp 4 rechts_positive",
    "Zwelling_mcp 5 links_negative",
    "Zwelling_mcp 5 links_positive",
    "Zwelling_mcp 5 rechts_negative",
    "Zwelling_mcp 5 rechts_positive",
    "Zwelling_mtp 1 links_negative",
    "Zwelling_mtp 1 links_positive",
    "Zwelling_mtp 1 rechts_negative",
    "Zwelling_mtp 1 rechts_positive",
    "Zwelling_mtp 2 links_negative",
    "Zwelling_mtp 2 links_positive",
    "Zwelling_mtp 2 rechts_negative",
    "Zwelling_mtp 2 rechts_positive",
    "Zwelling_mtp 3 links_negative",
    "Zwelling_mtp 3 links_positive",
    "Zwelling_mtp 3 rechts_negative",
    "Zwelling_mtp 3 rechts_positive",
    "Zwelling_mtp 4 links_negative",
    "Zwelling_mtp 4 links_positive",
    "Zwelling_mtp 4 rechts_negative",
    "Zwelling_mtp 4 rechts_positive",
    "Zwelling_mtp 5 links_negative",
    "Zwelling_mtp 5 links_positive",
    "Zwelling_mtp 5 rechts_negative",
    "Zwelling_mtp 5 rechts_positive",
    "Zwelling_onderste spronggewricht links_negative",
    "Zwelling_onderste spronggewricht links_positive",
    "Zwelling_onderste spronggewricht rechts_negative",
    "Zwelling_onderste spronggewricht rechts_positive",
    "Zwelling_pip 2 links hand_negative",
    "Zwelling_pip 2 links hand_positive",
    "Zwelling_pip 2 rechts hand_negative",
    "Zwelling_pip 2 rechts hand_positive",
    "Zwelling_pip 3 links hand_negative",
    "Zwelling_pip 3 links hand_positive",
    "Zwelling_pip 3 rechts hand_negative",
    "Zwelling_pip 3 rechts hand_positive",
    "Zwelling_pip 4 links hand_negative",
    "Zwelling_pip 4 links hand_positive",
    "Zwelling_pip 4 rechts hand_negative",
    "Zwelling_pip 4 rechts hand_positive",
    "Zwelling_pip 5 links hand_negative",
    "Zwelling_pip 5 links hand_positive",
    "Zwelling_pip 5 rechts hand_negative",
    "Zwelling_pip 5 rechts hand_positive",
    "Zwelling_pols L_negative",
    "Zwelling_pols L_positive",
    "Zwelling_pols R_negative",
    "Zwelling_pols R_positive",
    "Zwelling_schouder L_negative",
    "Zwelling_schouder L_positive",
    "Zwelling_schouder R_negative",
    "Zwelling_schouder R_positive",
    "Zwelling_sternoclaviculair L_negative",
    "Zwelling_sternoclaviculair L_positive",
    "Zwelling_sternoclaviculair R_negative",
    "Zwelling_sternoclaviculair R_positive",
    "Zwelling_tarsometatarsaal L_negative",
    "Zwelling_tarsometatarsaal L_positive",
    "Zwelling_tarsometatarsaal R_negative",
    "Zwelling_tarsometatarsaal R_positive",
    "Zwelling_temporomandibulair L_negative",
    "Zwelling_temporomandibulair L_positive",
    "Zwelling_temporomandibulair R_negative",
    "Zwelling_temporomandibulair R_positive",
    "Pijn_Elleboog L_negative",
    "Pijn_Elleboog L_positive",
    "Pijn_IP links_negative",
    "Pijn_IP links_positive",
    "Pijn_IP rechts_negative",
    "Pijn_IP rechts_positive",
    "Pijn_acromioclaviaculair L_negative",
    "Pijn_acromioclaviaculair L_positive",
    "Pijn_acromioclaviaculair R_negative",
    "Pijn_acromioclaviaculair R_positive",
    "Pijn_bovenste spronggewicht links_negative",
    "Pijn_bovenste spronggewicht links_positive",
    "Pijn_bovenste spronggewricht rechts_negative",
    "Pijn_bovenste spronggewricht rechts_positive",
    "Pijn_dip 2 links_negative",
    "Pijn_dip 2 links_positive",
    "Pijn_dip 2 rechts_negative",
    "Pijn_dip 2 rechts_positive",
    "Pijn_dip 3 links_negative",
    "Pijn_dip 3 links_positive",
    "Pijn_dip 3 rechts_negative",
    "Pijn_dip 3 rechts_positive",
    "Pijn_dip 4 links_negative",
    "Pijn_dip 4 links_positive",
    "Pijn_dip 4 rechts_negative",
    "Pijn_dip 4 rechts_positive",
    "Pijn_dip 5 links_negative",
    "Pijn_dip 5 links_positive",
    "Pijn_dip 5 rechts_negative",
    "Pijn_dip 5 rechts_positive",
    "Pijn_elleboog R_negative",
    "Pijn_elleboog R_positive",
    "Pijn_heup links_negative",
    "Pijn_heup links_positive",
    "Pijn_heup rechts_negative",
    "Pijn_heup rechts_positive",
    "Pijn_knie links_negative",
    "Pijn_knie links_positive",
    "Pijn_knie rechts_negative",
    "Pijn_knie rechts_positive",
    "Pijn_mcp 1 links_negative",
    "Pijn_mcp 1 links_positive",
    "Pijn_mcp 1 rechts_negative",
    "Pijn_mcp 1 rechts_positive",
    "Pijn_mcp 2 links_negative",
    "Pijn_mcp 2 links_positive",
    "Pijn_mcp 2 rechts_negative",
    "Pijn_mcp 2 rechts_positive",
    "Pijn_mcp 3 links_negative",
    "Pijn_mcp 3 links_positive",
    "Pijn_mcp 3 rechts_negative",
    "Pijn_mcp 3 rechts_positive",
    "Pijn_mcp 4 links_negative",
    "Pijn_mcp 4 links_positive",
    "Pijn_mcp 4 rechts_negative",
    "Pijn_mcp 4 rechts_positive",
    "Pijn_mcp 5 links_negative",
    "Pijn_mcp 5 links_positive",
    "Pijn_mcp 5 rechts_negative",
    "Pijn_mcp 5 rechts_positive",
    "Pijn_mtp 1 links_negative",
    "Pijn_mtp 1 links_positive",
    "Pijn_mtp 1 rechts_negative",
    "Pijn_mtp 1 rechts_positive",
    "Pijn_mtp 2 links_negative",
    "Pijn_mtp 2 links_positive",
    "Pijn_mtp 2 rechts_negative",
    "Pijn_mtp 2 rechts_positive",
    "Pijn_mtp 3 links_negative",
    "Pijn_mtp 3 links_positive",
    "Pijn_mtp 3 rechts_negative",
    "Pijn_mtp 3 rechts_positive",
    "Pijn_mtp 4 links_negative",
    "Pijn_mtp 4 links_positive",
    "Pijn_mtp 4 rechts_negative",
    "Pijn_mtp 4 rechts_positive",
    "Pijn_mtp 5 links_negative",
    "Pijn_mtp 5 links_positive",
    "Pijn_mtp 5 rechts_negative",
    "Pijn_mtp 5 rechts_positive",
    "Pijn_onderste spronggewricht links_negative",
    "Pijn_onderste spronggewricht links_positive",
    "Pijn_onderste spronggewricht rechts_negative",
    "Pijn_onderste spronggewricht rechts_positive",
    "Pijn_pip 2 links hand_negative",
    "Pijn_pip 2 links hand_positive",
    "Pijn_pip 2 rechts hand_negative",
    "Pijn_pip 2 rechts hand_positive",
    "Pijn_pip 3 links hand_negative",
    "Pijn_pip 3 links hand_positive",
    "Pijn_pip 3 rechts hand_negative",
    "Pijn_pip 3 rechts hand_positive",
    "Pijn_pip 4 links hand_negative",
    "Pijn_pip 4 links hand_positive",
    "Pijn_pip 4 rechts hand_negative",
    "Pijn_pip 4 rechts hand_positive",
    "Pijn_pip 5 links hand_negative",
    "Pijn_pip 5 links hand_positive",
    "Pijn_pip 5 rechts hand_negative",
    "Pijn_pip 5 rechts hand_positive",
    "Pijn_pols L_negative",
    "Pijn_pols L_positive",
    "Pijn_pols R_negative",
    "Pijn_pols R_positive",
    "Pijn_schouder L_negative",
    "Pijn_schouder L_positive",
    "Pijn_schouder R_negative",
    "Pijn_schouder R_positive",
    "Pijn_sternoclaviculair L_negative",
    "Pijn_sternoclaviculair L_positive",
    "Pijn_sternoclaviculair R_negative",
    "Pijn_sternoclaviculair R_positive",
    "Pijn_tarsometatarsaal L_negative",
    "Pijn_tarsometatarsaal L_positive",
    "Pijn_tarsometatarsaal R_negative",
    "Pijn_tarsometatarsaal R_positive",
    "Pijn_temporomandibulair L_negative",
    "Pijn_temporomandibulair L_positive",
    "Pijn_temporomandibulair R_negative",
    "Pijn_temporomandibulair R_positive",
    "RF",
    "aCCP",
    "Sex",
    "Age_Early",
    "Age_Late",
];
const lnum = ["Leuko", "Hb", "MCV", "Trom", "BSE", "Age"];
const expectedOrderForModel = ["PATNR"].concat(lnum).concat(lcat);

export { expectedColumnInFile, expectedOrderForModel };
