export const Joints: Coordinate[] = [
    { id: "ac_left", label: "Acromioclavicular Left", x: 846, y: 296, z: 30 },
    { id: "ac_right", label: "Acromioclavicular Right", x: 594, y: 314, z: 30 },
    { id: "ank_left", label: "Ankle Left", x: 808, y: 1447, z: 110 },
    { id: "ank_right", label: "Ankle Right", x: 644, y: 1425, z: 110 },
    {
        id: "dip2_left",
        label: "Distal Interphalangeal II Left",
        x: 1210,
        y: 1132,
        z: 80,
    },
    {
        id: "dip2_right",
        label: "Distal Interphalangeal II Right",
        x: 255,
        y: 1230,
        z: 80,
    },
    {
        id: "dip3_left",
        label: "Distal Interphalangeal III Left",
        x: 1303,
        y: 1059,
        z: 80,
    },
    {
        id: "dip3_right",
        label: "Distal Interphalangeal III Right",
        x: 152,
        y: 1168,
        z: 80,
    },
    {
        id: "dip4_left",
        label: "Distal Interphalangeal IV Left",
        x: 1346,
        y: 980,
        z: 80,
    },
    {
        id: "dip4_right",
        label: "Distal Interphalangeal IV Right",
        x: 99,
        y: 1101,
        z: 80,
    },
    {
        id: "dip5_left",
        label: "Distal Interphalangeal V Left",
        x: 1352,
        y: 875,
        z: 80,
    },
    {
        id: "dip5_right",
        label: "Distal Interphalangeal V Right",
        x: 96,
        y: 1005,
        z: 80,
    },
    { id: "el_left", label: "Elbow Left", x: 543, y: 584, z: 130 },
    { id: "el_right", label: "Elbow Right", x: 914, y: 550, z: 130 },
    {
        id: "pip1_left",
        label: "Proximal Interphalangeal I Thumb Left",
        x: 1047,
        y: 1076,
        z: 80,
    },
    {
        id: "pip1_right",
        label: "Proximal Interphalangeal I Thumb Right",
        x: 409,
        y: 1148,
        z: 80,
    },
    { id: "kn_left", label: "Knee Left", x: 815, y: 1112, z: 110 },
    { id: "kn_right", label: "Knee Right", x: 653, y: 1117, z: 110 },
    {
        id: "mcp1_left",
        label: "Metacarpophalangeal I Left",
        x: 978,
        y: 988,
        z: 80,
    },
    {
        id: "mcp1_right",
        label: "Metacarpophalangeal I Right",
        x: 467,
        y: 1051,
        z: 80,
    },
    {
        id: "mcp2_left",
        label: "Metacarpophalangeal II Left",
        x: 1015,
        y: 918,
        z: 80,
    },
    {
        id: "mcp2_right",
        label: "Metacarpophalangeal II Right",
        x: 418,
        y: 997,
        z: 80,
    },
    {
        id: "mcp3_left",
        label: "Metacarpophalangeal III Left",
        x: 1086,
        y: 877,
        z: 80,
    },
    {
        id: "mcp3_right",
        label: "Metacarpophalangeal III Right",
        x: 346,
        y: 961,
        z: 80,
    },
    {
        id: "mcp4_left",
        label: "Metacarpophalangeal IV Left",
        x: 1134,
        y: 812,
        z: 80,
    },
    {
        id: "mcp4_right",
        label: "Metacarpophalangeal IV Right",
        x: 291,
        y: 904,
        z: 80,
    },
    {
        id: "mcp5_left",
        label: "Metacarpophalangeal V Left",
        x: 1182,
        y: 749,
        z: 80,
    },
    {
        id: "mcp5_right",
        label: "Metacarpophalangeal V Right",
        x: 234,
        y: 848,
        z: 80,
    },
    {
        id: "mtp1_left",
        label: "Metatarsophalangeal I Left",
        x: 779,
        y: 1624,
        z: 80,
    },
    {
        id: "mtp1_right",
        label: "Metatarsophalangeal I Right",
        x: 606,
        y: 1603,
        z: 80,
    },
    {
        id: "mtp2_left",
        label: "Metatarsophalangeal II Left",
        x: 855,
        y: 1600,
        z: 80,
    },
    {
        id: "mtp2_right",
        label: "Metatarsophalangeal II Right",
        x: 524,
        y: 1590,
        z: 80,
    },
    {
        id: "mtp3_left",
        label: "Metatarsophalangeal III Left",
        x: 928,
        y: 1570,
        z: 80,
    },
    {
        id: "mtp3_right",
        label: "Metatarsophalangeal III Right",
        x: 454,
        y: 1554,
        z: 80,
    },
    {
        id: "mtp4_left",
        label: "Metatarsophalangeal IV Left",
        x: 984,
        y: 1512,
        z: 80,
    },
    {
        id: "mtp4_right",
        label: "Metatarsophalangeal IV Right",
        x: 388,
        y: 1505,
        z: 80,
    },
    {
        id: "mtp5_left",
        label: "Metatarsophalangeal V Left",
        x: 1039,
        y: 1457,
        z: 80,
    },
    {
        id: "mtp5_right",
        label: "Metatarsophalangeal V Right",
        x: 338,
        y: 1444,
        z: 80,
    },
    {
        id: "pip2_left",
        label: "Proximal Interphalangeal II Left",
        x: 1114,
        y: 1053,
        z: 80,
    },
    {
        id: "pip2_right",
        label: "Proximal Interphalangeal II Right",
        x: 334,
        y: 1127,
        z: 80,
    },
    {
        id: "pip3_left",
        label: "Proximal Interphalangeal III Left",
        x: 1215,
        y: 985,
        z: 80,
    },
    {
        id: "pip3_right",
        label: "Proximal Interphalangeal III Right",
        x: 236,
        y: 1083,
        z: 80,
    },
    {
        id: "pip4_left",
        label: "Proximal Interphalangeal IV Left",
        x: 1270,
        y: 911,
        z: 80,
    },
    {
        id: "pip4_right",
        label: "Proximal Interphalangeal IV Right",
        x: 172,
        y: 1018,
        z: 80,
    },
    {
        id: "pip5_left",
        label: "Proximal Interphalangeal V Left",
        x: 1292,
        y: 821,
        z: 80,
    },
    {
        id: "pip5_right",
        label: "Proximal Interphalangeal V Right",
        x: 141,
        y: 932,
        z: 80,
    },
    { id: "wr_left", label: "Wrist Left", x: 986, y: 705, z: 110 },
    { id: "wr_right", label: "Wrist Right", x: 498, y: 779, z: 110 },
    { id: "sh_left", label: "Shoulder Left", x: 880, y: 345, z: 110 },
    { id: "sh_right", label: "Shoulder Right", x: 552, y: 361, z: 110 },
    { id: "sc_left", label: "Sternoclavicular Left", x: 756, y: 316, z: 50 },
    { id: "sc_right", label: "Sternoclavicular Right", x: 675, y: 320, z: 50 },
    { id: "tar_left", label: "Tarsus Left", x: 865, y: 1490, z: 40 },
    { id: "tar_right", label: "Tarsus Right", x: 576, y: 1466, z: 40 },
    { id: "tm_left", label: "Temporomandibular Left", x: 772, y: 194, z: 80 },
    { id: "tm_right", label: "Temporomandibular Right", x: 652, y: 210, z: 80 },
    { id: "hip_left", label: "Hip Left", x: 629, y: 791, z: 0 },
    { id: "hip_right", label: "Hip Right", x: 799, y: 783, z: 0 },
];

interface Coordinate {
    id: string;
    label?: string;
    x: number;
    y: number;
    z: number;
}

export type { Coordinate };
